In [1]:
print("Hi")
#现在是在pycharm里使用jupyter notebook

Hi


# Numpy ndarray
## 1.ndarray特性
### 多维性

In [2]:
import numpy as np
# 后面的as np是什么意思呢？
# 其实这一句代码等效于：
#import numpy
#np = numpy 其实就是让以后调用numpy的时候可以只用打np两个字母，省事。

In [3]:
arr = np.array([1,2,3,4,5]) #创建1维ndarray数组。np.array就是创建数组的函数
print(arr)
print("arr的维度", arr.ndim) #这行代码可以打印出arr的维度(ndim: number of dimensions)，本例中打印结果是1

[1 2 3 4 5]
arr的维度 1


In [4]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


### 同质性

In [5]:
arr1 = np.array([1,2,"三",4,5]) #如果数组里有不同的数据类型，会被强行转化为一致
print(arr1) #你会发现打印出来的都成了字符串
arr2 = np.array([1,2,3.0,4,5])
print(arr2) #这个会被全部转换成浮点数，但小数点后的0会被省略

['1' '2' '三' '4' '5']
[1. 2. 3. 4. 5.]


## 2.ndarray的属性

In [6]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.shape) #数组的形状：(行数,列数)
print(arr.ndim) #维数
print(arr.dtype) #数组中元素得到类型
print(arr.size) #数组中所有元素的个数
print(arr.T) #这是转置，参考矩阵的转置·

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2
int64
10
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


## 3.ndarray的创建

In [7]:
#上面的使用np.array方法创建数组是基础创建方法
arr = np.array([1,2,3])
print (arr)
#实际上这串代码等效于：
list_1 = [1,2,3]
arr_1 = np.array(list_1)
print (arr_1)


[1 2 3]
[1 2 3]


### np.copy

In [8]:
#np.copy的用法
arr_2 = np.copy(arr_1)
#这里是用arr_1给arr_2赋值，但是这两个是两个独立的数组，互不干扰
arr_2[0] = 4 #数组里依然可以用索引，看来索引的用处远比我之前广得多
print(arr_2)
print(arr_1)
#对比一下，看看arr_1是不是并没有受到arr_2更改的影响


[4 2 3]
[1 2 3]


In [9]:
# 顺带一提，如果你运行以下代码：
arr = np.array([3,4,5])
print(arr)
#并不会因为前面你已经给arr赋值为[1 2 3]而显示重复报错，还是可以打印出[3 4 5]
#但是，如果你再在一个新的cell里print(arr)，打印出来的arr值取决于你最后一次运行了哪个cell里的arr赋值语句
#换句话讲，虽然说cell之间存在记忆，但是只会保留最新的记忆，旧记忆会被新记忆取代
#因此最好不要重复使用同一个名字

[3 4 5]


### 特殊数组的创建

In [10]:
#预定义形状，也就是行数和列数

# 全0数组
arr_all_0 = np.zeros((2,3)) #np.zeros()里的(2,3)为什么还要套一个括号？
                            #因为(2,3)就是一个数组.shape的输出结果，自然得把括号带上。
                            #第一层括号是方法名自带的，第二层是数组.shape自带的
print(arr_all_0)
print(arr_all_0.dtype) #为什么会以浮点数格式打印出来？鬼知道。
# 全1数组
arr_all_1 = np.ones((2,3))
print(arr_all_1) #依旧浮点数格式
#空数组
arr_empty = np.empty((2,3), dtype=int)  #用dtype就可以决定我们要输出什么类型的数据
print(arr_empty)
print(arr_empty) #随机用一个数填充？
#填满数组
arr_full = np.full((2,3),2026) #后面的2026是指用2026填满这个2行3列的数组
print(arr_full) #奇怪，到这里就又变回整数了

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[1. 1. 1.]
 [1. 1. 1.]]
[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
[[2026 2026 2026]
 [2026 2026 2026]]


In [11]:
#用0把上面的arr_full里所有的2026替换掉
arr_full_0 = np.zeros_like(arr_full)
print(arr_full_0)
#如果你想换成1全部替代掉，那就是把zeros换成ones
#如果你想用其他数字呢？
arr_full_23 = np.full_like(arr_full,23) #还有np.full_like可用
print(arr_full_23)

[[0 0 0]
 [0 0 0]]
[[23 23 23]
 [23 23 23]]


### 等差数列与等间隔数列

In [12]:
#等差数列：np.arange
arr_range = np.arange(2,10,2) #这里和range的用法是同理的，同样包括开头不包括结尾
                              #最后的2为步长（步长也可以是浮点数
print(arr_range)

[2 4 6 8]


In [13]:
#等间隔数列：np.linspace
arr_linspace = np.linspace(1,10,4,dtype=int) #和range不同，结尾的10也是包括的，
                                   #而最后的4是指你要让这个数组里有几个元素，因此这个数字只能是整数
print(arr_linspace) #默认输出浮点数
#这玩意本质上还是等差数列，只是创建逻辑和np.arange不一样。这个好像更符合人类的思维惯性

[ 1  4  7 10]


In [14]:
#等对数间隔数列
arr_log = np.logspace(0,1,3,base=3) #base为10时省略不写
#np.logspace(start,stop,num,base),要想真正理解，得结合前面的np.linspace
#本质上，是先进行了: 指数=np.linspace(start,stop,num),
#然后把得到的"指数"这个等间隔数组作为base的指数，求出一个同样有num个元素的新数组
print(arr_log)

[1.         1.73205081 3.        ]


### 特殊矩阵的生成

In [15]:
#标量 0维 单个数字 无行列之说
#向量 1维 单行或单列数组
#矩阵 2维 有行有列
#张量 >=3维

In [16]:
#单位矩阵：主对角线上数字为1，其他的数字为0
arr_eye = np.eye(3,dtype=int)
print(arr_eye)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [17]:
#对角矩阵：主对角线上依次为你给的数字，其它为0
arr_diag = np.diag([1,2,3])
print(arr_diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [18]:
#随机数组

#生成0到1之间的随机浮点数
arr_random = np.random.rand(2,3)
print(arr_random) #为什么会是0~1之间呢？
#生成指定区间的随机浮点数
arr_random_1 = np.random.uniform(1,2,(2,3))
print(arr_random_1)
#生成指定区间的随机整数
arr_random_2 = np.random.randint(1,20,(2,3))
print(arr_random_2)

[[0.71430856 0.367307   0.49175364]
 [0.62895507 0.72162218 0.84764721]]
[[1.25340939 1.65825087 1.96289615]
 [1.18430621 1.03519762 1.09972634]]
[[ 9  1 12]
 [18  9  6]]


In [19]:
#符合正态分布的随机数列
arr_random_randn = np.random.randn(2,3)
print(arr_random_randn)
#我不知道这个是怎么体现正态分布的（疑惑

[[ 1.34241548 -0.76259767 -0.51891526]
 [-0.85678083 -0.2058816  -0.90926974]]


## 4.ndarray的数据类型

In [20]:
#布尔类型 bool
#整数 int uint
#浮点数 float
#复数complex
#这些前缀要加np.

In [21]:
arr_bool = np.array([0,1,0,1],dtype=bool)
print(arr_bool)
# 在python里，非0的数字会被映射为True，0会被映射为False
arr_int8 = np.array([1,3,7,-127],dtype=np.int8)
# 由于int8、16,uint以及float16等等是numpy独有的数据类型，所以前面要加上np.
print(arr_int8)
# int8包含从-128到127之间的256个整数，uint8包含从0到255之间的256个整数。把8换成16，32，64同理。
# 不遵守就会报错。
arr_float64 = np.array([1.0,3.3,3.141592653589793834,2],dtype=np.float64)
print(arr_float64)
# float16、32、64使得float的精度（保留小数点后几位）逐级递增。
# 与int不同，float精度如果过高只是会保留有限位数，不会报错



[False  True False  True]
[   1    3    7 -127]
[1.         3.3        3.14159265 2.        ]


## 5.索引与切片

In [22]:
# 一维数组的索引与切片
arr_5_1 = np.random.randint(1,100,20)
print(arr_5_1)
print(arr_5_1[3])
print(arr_5_1[2:5]) # :可以用于获取某一范围的数组，
                    # [a:b]指的是从arr[a]到arr[b](不包含）之间的所有元素组成的数组
                    # 如果是[a:],那就是取arr[a]以后所有元素组成的数组；[:b]同理;[:]就是整个原数组


[98 93 83 73 24 40 71 28  7 65 17 89 83 86 74 70 30  3 66 36]
73
[83 73 24]


In [23]:
# 布尔索引，运用逻辑运算来筛选符合条件的元素组成的数组
print(arr_5_1 > 30) # 这种情况下，输出的是一个布尔数组，由布尔值组成的数组
print(arr_5_1[arr_5_1 > 30]) # 这种情况下，是原数组经过布尔数组这个筛子后的输出结果
print(arr_5_1[(arr_5_1 > 30) & (arr_5_1 < 70)])
# 为什么这里不能用and?(疑惑
# 已经知道，(arr_5_1 > 30)的输出结果是一个布尔数组，(arr_5_1 < 70)同理
# and根本没法对两个布尔数组进行条件判断

# &，讲简单点，就是对于两个布尔数组中的对应位置元素，挨个地进行比较（专业说法是元素级比较）。
# 如果两个都是True，就合成为True，否则是False。嘿这里竟然和and很像。
# |，就是or，参考上面的理解。




[ True  True  True  True False  True  True False False  True False  True
  True  True  True  True False False  True  True]
[98 93 83 73 40 71 65 89 83 86 74 70 66 36]
[40 65 66 36]


In [24]:
#切片
print(arr_5_1 [slice(2,5)])
#这个目前看来是和[2:5]的索引等效的

[83 73 24]


In [25]:
#二维数组的索引与切片
arr_5_2 = np.random.randint(1,100,(4,5))
print(arr_5_2)

[[18 11  4 47 42]
 [71 82 63 73 33]
 [73 14 79 65 55]
 [96 42 19 23 37]]


In [26]:
#索引
print(arr_5_2[2,3]) # 第三行第四列
print(arr_5_2[1:3,2:4]) # 取位于第二行到第三行，且第三列到第四列的区块
print(arr_5_2[1,]) #直接取第二行
# 牢记，这一切的基础是索引，而第一个元素在索引中的序号为0，务必记住！

65
[[63 73]
 [79 65]]
[71 82 63 73 33]


In [27]:
#布尔索引
print(arr_5_2[arr_5_2 > 30])  # 这样会返回一个一维结果，因为你没有给出具体位置，因此默认对整体进行判断
print(arr_5_2[1,] > 30) # 这样打印的结果是布尔数组,可以作为布尔索引
print(arr_5_2[1,] [arr_5_2[1,]> 30]) # 这样就会是想要的结果。
                                     # 我们已经知道，[arr_5_2[1,]> 30]的输出结果是布尔数组
                                     # 而这个布尔数组，可以起一个数据筛子的作用，是True就输出，False就筛掉
                                     # 初始数组[布尔数组]，就是这个筛选的过程。
                                     # 实际上，前面的布尔索引道理是一样的。
                                     # 所以说，布尔索引，是一个有！筛选！功能的索引。
                                     # 索引里面是一个布尔数组，而这个布尔数组里的True和False则决定保留或不通过。


[47 42 71 82 63 73 33 73 79 65 55 96 42 37]
[ True  True  True  True  True]
[71 82 63 73 33]


## 6.ndarray的运算

### 算术运算

In [28]:
arr_6_1 = np.array([1,2,3])
arr_6_2 = np.array([4,5,6])
print(arr_6_1 + arr_6_2) # 数组的相加是逐个元素之间进行相加
print(arr_6_1 - arr_6_2)
print(arr_6_1 * arr_6_2)
print(arr_6_1 / arr_6_2)
print(arr_6_1 ** 2)
#以加为例，实际上数组的相加用python直接表示则是：
list1 = [1,2,3]
list2 = [4,5,6]
for i in range(len(list1)):
    list1[i] = list1[i] + list2[i]
    print(list1)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[5, 2, 3]
[5, 7, 3]
[5, 7, 9]


In [29]:
arr_6_3 = np.random.randint(1,20,(2,3))
print(arr_6_3)
arr_6_4 = np.random.randint(1,20,(2,3))
print(arr_6_4)

[[13 16  3]
 [ 5 16 13]]
[[ 8 14 15]
 [15 13 11]]


In [30]:
print(arr_6_3 + arr_6_4) # 二维数组的算术运算类似

[[21 30 18]
 [20 29 24]]


In [31]:
print (arr_6_1 + 3)
# 有没有发现，数组可以直接和一个数字相加。
# 按理讲数组和数字不应该是同一个数据类型，为何还能直接用加号相连呢?

[4 5 6]


In [32]:
# 广播机制（奇怪的名字）
print(arr_6_1 + arr_6_3) # 一维数组还可以和二维数组相加
# 更极端的
arr_6_5 = np.array([[1],[2],[3]]) # 一个3*1的数组
print(arr_6_1 * arr_6_5)
# 广播机制成立的前提条件是，两个数组每个维度上都应：大小相等或者其中一个大小为1。比如3*1的数组和2*3的数组不会触发广播机制
# 当有一个数组在某一维度上大小为1，numpy会在计算时“按需扩展”这个维度，其形式是进行复制
# 使得两个数组在逻辑上具有兼容的形状，从而完成逐元素运算（并不是真的复制数据）。

#arr_6_1和arr_6_5相加
#arr_6_1: 1 2 3 --> 1 2 3
#                   1 2 3
#                   1 2 3
#arr_6_5:1 --> 1 2 3
#        2     1 2 3
#        3     1 2 3
#然后相加
# 回头看，数组可以和一个数字直接相加，是不是就更好理解了呢

[[14 18  6]
 [ 6 18 16]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


### 矩阵运算

In [33]:
arr_6_6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_6_6)
arr_6_7 = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(arr_6_7)
print(arr_6_6 @ arr_6_7) # @是矩阵的乘法运算符，具体怎么算参考线性代数

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


### 数组的拼接

In [35]:
arr_7_1 = np.array([1,2,3])
arr_7_2 = np.array([4,5,6])
arr_7_3 = np.concatenate([arr_7_1,arr_7_2])
print(arr_7_3)

[1 2 3 4 5 6]
