# Numpy常用函数

## 1.基本数学函数

In [2]:
import numpy as np

In [3]:
# 计算平方根
print(np.sqrt(9))
arr_1_1 = np.array([1,4,9])
print((np.sqrt(arr_1_1)))
# 计算指数
print(np.exp(1)) # 好像就是f(x)=e^x
# 计算自然对数
print(np.log(3)) #以e为底数计算对数，f(x)=ln(x)
# 计算三角函数,其中pai用np.pi表示
print(np.sin(np.pi/2))
print(np.cos(np.pi))
# 计算幂
arr_1_2 = np.array([1,-2,3,-4])
print(np.power(2,9)) # np.power(底数,指数)
print(np.power(arr_1_2,2)) # 输出结果是一个新数组


3.0
[1. 2. 3.]
2.718281828459045
1.0986122886681098
1.0
-1.0
512
[ 1  4  9 16]


In [4]:
# 计算绝对值
arr_1_2 = np.array([1,-2,3,-4])
print(np.abs(arr_1_2)) # 输出结果是一个新数组
print(np.sum(np.abs(arr_1_2)))
# 四舍五入
print(np.round([3.14,4.26,3.89]))
    # 注意这个四舍五入和数学上的有点差别
print(np.round([4.5,4.51,4.501])) # 这个叫做取偶，如果是a.5这个数字，a为偶数输出结果为a，a为奇数输出结果为a+1
# 向上取整和向下取整
print(np.ceil([3.14,4.26,3.89])) # 天花板，向上取整
print(np.floor([3.14,4.26,3.89])) # 地板，向下取整（还挺形象

[1 2 3 4]
10
[3. 4. 4.]
[4. 5. 5.]
[4. 5. 4.]
[3. 4. 3.]


In [5]:
# 检测缺失值NaN NaN用于表示缺失值
np.isnan([1,2,np.nan,3]) # np.isnan用于检测是否为NaN，输出布尔值（布尔数组）；np.nan表示NaN

array([False, False,  True, False])

## 2.统计函数

In [6]:
# 以一个一维数组为示例数据，作为下列所有函数的示例
arr_2_1 = np.random.randint(1,100,(1,50))
print(arr_2_1)
# 单独作为一个cell，使其不会乱变

[[37 76 96 93  6 24  2 45 22 31 97  5  9 63 78 26 45  3 17 22 17  4 85 21
  70 63 97 95 72 84 44  5  9  1 99  3 65 29 63 75 76 79 93 37  4 40  7 78
  82 50]]


In [7]:
# 求和
print(np.sum(arr_2_1))
# 计算平均值
print(np.mean(arr_2_1)) # 还可以用np.average方法，甚至更好记忆
# 计算中位数
print(np.median(arr_2_1))
# 计算方差和标准差
print(np.var(arr_2_1)) # 方差
print(np.std(arr_2_1)) # 标准差
# 计算最值以及最值在数组中所处的位置
print(np.max(arr_2_1),np.argmax(arr_2_1))
print(np.min(arr_2_1),np.argmin(arr_2_1))

2344
46.88
44.5
1105.9056
33.25515899826672
99 34
1 33


In [8]:
# 对于以上统计运算，在二维数组中使用还可以在单行/单列运行
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(np.sum(arr_2d, axis=0)) # 对arr_2d的每一列进行求和
print(np.mean(arr_2d, axis=1)) #对arr_2d的每一行求平均值
# 在这两种情况下，输出的结果都会是一个一维数组，这在数据分析中可以与广播机制结合运用

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[2. 5. 8.]


In [9]:
# 计算分位数
arr_2_2 = np.array([1,2,4,5,6])
print(np.percentile(arr_2_2,25)) # 下四分位数
# np.percentile(arr,num),num为百分数，具体含义参考分位数知识
# 累积和，累积积
print(np.cumsum(arr_2_2)) # 输出结果为一个新数组，每个位置上的新数字为原数字与其在原数组前面所有数字之和
print(np.cumprod(arr_2_2)) # 把累积和里的求和换成乘积


2.0
[ 1  3  7 12 18]
[  1   2   8  40 240]


## 3.比较函数

In [10]:
arr_3_1 =np.random.randint(1,100,(1,10))
print(arr_3_1)
arr_3_2 = np.random.randint(1,100,(1,10))
print(arr_3_2)

[[85  1  7  3  9 44 10  4 74 86]]
[[18 75 52 96 31 25 68 91 91 17]]


In [11]:
# 数组中各个元素是否大于、小于或等于某一数值
print(np.greater(arr_3_1,50))
# 这和print(arr_3_1 > 50)有区别吗？
print(np.less(arr_3_1,50))
print(np.equal(arr_3_1,48))
# 这些函数还可以用于比较同形状的数组
print(np.greater(arr_3_1,arr_3_2))

[[ True False False False False False False False  True  True]]
[[False  True  True  True  True  True  True  True False False]]
[[False False False False False False False False False False]]
[[ True False False False False  True False False False  True]]


In [12]:
# 与、或、非的运算(and or not)
# 在数组里，逻辑判断的依据是是否有一个是0，
# 对数值数组，NumPy 会把 0 视为 False，非 0 视为 True，然后进行逐元素逻辑运算
arr_3_3 = np.array([1,1,0])
arr_3_4 = np.array([1,0,0])
print(np.logical_and(arr_3_3,arr_3_4)) # and:只要相同位置的元素有一个是0就输出False
print(np.logical_or(arr_3_3,arr_3_4)) # or:只有相同位置的元素两个都是0才输出False
print(np.logical_not(arr_3_3)) # not:只针对一个数组进行操作，判断是不是不为0.不为0输出True，否则为False
# 以上都是输出布尔数组

# 检查元素是否有一个为True
print(np.any(arr_3_3))
# 检查元素是否有都为为True
print(np.all(arr_3_4))
# 这两个都是输出一个布尔值

[ True False False]
[ True  True False]
[False False  True]
True
False


In [13]:
# 自定义条件并执行操作
arr_3_5 = np.array([1,2,3,4,5])
print(np.where(arr_3_5 > 3,arr_3_5,1))
# 它像是numpy里的if-elif-else，在数组上对每一个元素进行条件分析
# 对每一个元素，如果条件成立，执行第二个参数；否则，执行第三个参数
# 类似于if，它也可以嵌套多个条件
print(np.where(
    arr_3_5 > 3,arr_3_5,np.where(
        arr_3_5 < 2,100,1),
))

[1 1 1 4 5]
[100   1   1   4   5]


In [14]:
# 我们来使用np.where写一个成绩水平筛查器
# 用随机数组生成学生们的成绩：
np.random.seed(0) # 这一步可以让随机数生成“固定的随机值”
                  # 因为numpy的随机数并不随机，它只是用固定的算法算出一系列看似随机的数字
                  # 因此，你设下的seed，相当于给numpy设置了一个初始刻度，使得numpy的算法从这个你给定的刻度开始生成
                  # 这样一来，生成的随机数就固定下来了。如果不固定，你每次重新执行，生成的数字就会变，这可不是什么好事
score_list = np.random.randint(1,100,(1,30))
# 显示出成绩表
print("成绩为：",score_list)
# 用优秀、及格、不及格对成绩进行划分
# 80分及以上为优秀，60分及以上80分以下为及格，其余的不及格
print(np.where(
    score_list > 80,"优秀",np.where(
        score_list >= 60,"及格","不及格"
    )
))

成绩为： [[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89 82 38 26 78
  73 10 21 81 70 80]]
[['不及格' '不及格' '及格' '及格' '及格' '不及格' '优秀' '不及格' '不及格' '优秀' '及格' '优秀' '优秀'
  '不及格' '不及格' '及格' '不及格' '优秀' '不及格' '优秀' '优秀' '不及格' '不及格' '及格' '及格' '不及格'
  '不及格' '优秀' '及格' '及格']]


## 4.排序函数

In [15]:
np.random.seed(0)
arr_4_1 = np.random.randint(1,100,20)
# 自动排序从小到大
print(arr_4_1)
print(np.sort(arr_4_1))
# 与np.max和np.min一样，np.sort也可以变成np.argsort来标注索引
print(np.argsort(arr_4_1))


[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6  9 17 11 12 19]


In [16]:
# 去重函数
print(np.unique(arr_4_1))
# 实际上它执行完去重后还会自动排序

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]
